- pom.xml
> Añadido a alvsangon2 como developer

- pom.xml
cambio en el nombre de grupo apartado A
> Cambio el nombre de grupo

- src/main/java/org/springframework/samples/petclinic/web/WelcomeController.java
- src/main/webapp/WEB-INF/jsp/welcome.jsp
> personalizacion página

- src/main/resources/db/hsqldb/data.sql
> Tarea del owner, se me habia olvidado añadirme una mascota

- src/main/java/org/springframework/samples/petclinic/model/Cuenta.java
- src/main/java/org/springframework/samples/petclinic/repository/CuentaRepository.java
- src/main/java/org/springframework/samples/petclinic/service/CuentaService.java
- src/main/java/org/springframework/samples/petclinic/web/ClienteController.java
- src/main/java/org/springframework/samples/petclinic/web/CuentaController.java
- src/main/webapp/WEB-INF/jsp/clientes/clientesList.jsp
- src/main/webapp/WEB-INF/jsp/clientes/createOrUpdateCuentaForm.jsp
> PRIMER SPRINT

- src/main/java/org/springframework/samples/petclinic/web/CuentaController.java
- src/main/webapp/WEB-INF/jsp/clientes/clientesList.jsp
- src/main/webapp/WEB-INF/jsp/clientes/createOrUpdateCuentaForm.jsp
intentando arreglas mi desastre
> he creado un post de ejemplo en clientes

- src/main/java/org/springframework/samples/petclinic/web/CocineroController.java
- src/main/resources/db/hsqldb/data.sql
- src/main/webapp/WEB-INF/jsp/cocineros/cocinerosList.jsp
- src/main/webapp/WEB-INF/jsp/cocineros/createOrUpdateCocinaForm.jsp
> Arreglado pequeño error del cocinero con el model attribute

- src/main/java/org/springframework/samples/petclinic/model/NivelSocio.java
- src/main/java/org/springframework/samples/petclinic/model/Oferta.java
- src/main/java/org/springframework/samples/petclinic/model/TamanoProducto.java
> Clase Oferta con NivelSocio y TamanoProducto que son sus enumerados.

- src/main/java/org/springframework/samples/petclinic/repository/ReservaRepository.java
- src/main/java/org/springframework/samples/petclinic/service/ReservaService.java
- src/main/java/org/springframework/samples/petclinic/web/ReservaController.java
- src/main/webapp/WEB-INF/tags/menu.tag
> Reserva se habia borrado del main lol

- src/main/java/org/springframework/samples/petclinic/model/Empleado.java
- src/main/java/org/springframework/samples/petclinic/model/Ingrediente.java
- src/main/java/org/springframework/samples/petclinic/service/OtrosService.java
- src/main/java/org/springframework/samples/petclinic/web/CocineroController.java
- src/main/java/org/springframework/samples/petclinic/web/OtrosController.java
- src/main/webapp/WEB-INF/jsp/Ingredientes/createOrUpdateIngredienteForm.jsp
- src/main/webapp/WEB-INF/jsp/Ingredientes/ingredientesList.jsp
- src/main/webapp/WEB-INF/jsp/cocineros/cocinerosList.jsp
> H-001 Gestionar Alta/Baja Cocinero

- src/main/less/header.less
- src/main/less/petclinic.less
- src/main/less/typography.less
- src/main/webapp/WEB-INF/jsp/exception.jsp
- src/main/webapp/WEB-INF/jsp/welcome.jsp
- src/main/webapp/WEB-INF/tags/menu.tag
- src/main/webapp/WEB-INF/tags/pivotal.tag
Estoy cambiando poco a poco la apariencia de la página
> pequeña modificacion less

- src/main/java/org/springframework/samples/petclinic/model/Cuenta.java
- src/main/java/org/springframework/samples/petclinic/service/ClienteService.java
- src/main/java/org/springframework/samples/petclinic/web/ClienteController.java
- src/main/java/org/springframework/samples/petclinic/web/CuentaValidator.java
- src/main/java/org/springframework/samples/petclinic/web/PetValidator.java
- src/main/java/org/springframework/samples/petclinic/web/ReservaController.java
- src/main/java/org/springframework/samples/petclinic/web/ReservaValidator.java
- src/main/webapp/WEB-INF/jsp/clientes/createOrUpdateCuentaForm.jsp
- src/test/java/org/springframework/samples/petclinic/service/ClienteServiceTests.java
Subo el validador de Cuenta ahora (le queda mostrar los errores y ya estaría) y he hecho las pruebas de ClienteService :)
> CuentaValidator y ClienteServiceTests

- src/main/java/org/springframework/samples/petclinic/web/ReclamacionController.java
- src/main/java/org/springframework/samples/petclinic/web/ReclamacionValidator.java
- src/main/webapp/WEB-INF/jsp/reclamaciones/createOrUpdateReclamacionForm.jsp
- src/test/java/org/springframework/samples/petclinic/service/OfertaServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/ReclamacionServiceTests.java
Pruebas de oferta (hay que corregirlas y completarlas).
Pequeños cambios en los jsp.
> Pruebas de reclamación, validator de reclamación.

- src/main/java/org/springframework/samples/petclinic/model/Oferta.java
- src/main/java/org/springframework/samples/petclinic/model/Pedido.java
- src/main/java/org/springframework/samples/petclinic/repository/OfertaRepository.java
- src/test/java/org/springframework/samples/petclinic/service/OfertaServiceTests.java
Modificación de clases OfertaRepository, Pedido y Oferta
> Prueba de insertar Oferta ya funciona.

- src/test/java/org/springframework/samples/petclinic/service/OfertaServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/ReclamacionServiceTests.java
Pruebas de insert y update Oferta hechas.
> Pruebas de ReclamacionService completadas.

- src/main/java/org/springframework/samples/petclinic/model/Reserva.java
- src/main/java/org/springframework/samples/petclinic/web/MesaValidator.java
- src/test/java/org/springframework/samples/petclinic/service/MesaServiceTests.java
Clase Reserva modificada (añadido cascade = CascadeType.ALL al
enumerate).
Habría que revisar el primer test del mesaServiceTests, ya que es el
único que da error.
> Corregido un error del MesaValidator.

- src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
- src/main/java/org/springframework/samples/petclinic/model/Cliente.java
- src/main/java/org/springframework/samples/petclinic/model/Cuenta.java
- src/main/java/org/springframework/samples/petclinic/model/User.java
- src/main/java/org/springframework/samples/petclinic/repository/ClienteRepository.java
- src/main/java/org/springframework/samples/petclinic/web/ClienteController.java
- src/main/java/org/springframework/samples/petclinic/web/OfertaValidator.java
- src/main/java/org/springframework/samples/petclinic/web/ReservaController.java
- src/main/resources/db/hsqldb/data.sql
- src/main/webapp/WEB-INF/jsp/cartas/verCarta.jsp
- src/main/webapp/WEB-INF/jsp/clientes/createOrUpdateCuentaForm.jsp
- src/main/webapp/WEB-INF/jsp/reservas/createOrUpdateReservaForm.jsp
- src/main/webapp/WEB-INF/jsp/welcome.jsp
He arreglado la edición de clientes de los datos personales y he arreglado el validador de reserva
> Validador reserva y edit clientes

- src/main/java/org/springframework/samples/petclinic/web/ReclamacionFormatter.java
- src/test/java/org/springframework/samples/petclinic/web/ReclamacionControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/ReclamacionFormatterTests.java
Pruebas de reclamación formatter (estas sí funcionan)
> Pruebas del controlador de reclamación (no funcionan)

- src/main/java/org/springframework/samples/petclinic/web/CartaController.java
- src/main/webapp/WEB-INF/jsp/pizzas/pizzasList.jsp
He arreglado que cuando se creaba una pizza nueva no se podía directamente meter en la carta. Ahora si se puede.
> Arreglos en carta

- src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
- src/main/java/org/springframework/samples/petclinic/model/Bebida.java
- src/main/java/org/springframework/samples/petclinic/model/Otros.java
- src/main/java/org/springframework/samples/petclinic/model/Pizza.java
- src/main/java/org/springframework/samples/petclinic/repository/BebidaRepository.java
- src/main/java/org/springframework/samples/petclinic/repository/OtrosRepository.java
- src/main/java/org/springframework/samples/petclinic/repository/PizzaRepository.java
- src/main/java/org/springframework/samples/petclinic/service/BebidaService.java
- src/main/java/org/springframework/samples/petclinic/service/OtrosService.java
- src/main/java/org/springframework/samples/petclinic/service/PizzaService.java
- src/main/java/org/springframework/samples/petclinic/web/CartaController.java
- src/main/webapp/WEB-INF/jsp/Otros/OtrosList.jsp
- src/main/webapp/WEB-INF/jsp/bebidas/bebidasList.jsp
- src/main/webapp/WEB-INF/jsp/cartas/verCarta.jsp
- src/main/webapp/WEB-INF/jsp/pizzas/pizzasList.jsp
- src/main/webapp/WEB-INF/jsp/welcome.jsp
He arreglado ciertas cosas de la carta. He arreglado los delete de carta con respecto a pizzas, bebidas y otros. Además, he tocado el security y algunas vistas porque he encontrado la manera de que solo ciertas autoridades puedan ver ciertos links para minimizar los fallos y facilitar la navegación.
> Arreglos en carta y cosas de seguridad

- src/main/java/org/springframework/samples/petclinic/repository/MesaRepository.java
- src/main/java/org/springframework/samples/petclinic/service/MesaService.java
- src/main/java/org/springframework/samples/petclinic/web/InformeController.java
- src/main/webapp/WEB-INF/jsp/informe/InformeMesasMasUsadas.jsp
> Informe mesas mas usadas faltan pruebas

- src/main/java/org/springframework/samples/petclinic/web/CocineroController.java
- src/main/java/org/springframework/samples/petclinic/web/CocineroValidator.java
- src/main/webapp/WEB-INF/jsp/cocineros/createOrUpdateCocinaForm.jsp
- src/test/java/org/springframework/samples/petclinic/web/CocineroControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/OfertaControllerTests.java
> Arreglando el validador de cocinero, el controlador y su test (no  se

- src/main/java/org/springframework/samples/petclinic/repository/IngredienteRepository.java
- src/main/java/org/springframework/samples/petclinic/repository/MesaRepository.java
- src/main/java/org/springframework/samples/petclinic/service/IngredienteService.java
- src/main/java/org/springframework/samples/petclinic/web/InformeController.java
- src/main/webapp/WEB-INF/jsp/informe/CaducidadIngredientes.jsp
> Informe Caducidad Clientes

- src/main/java/org/springframework/samples/petclinic/web/OfertaController.java
- src/main/java/org/springframework/samples/petclinic/web/OfertaValidator.java
- src/main/java/org/springframework/samples/petclinic/web/ReclamacionController.java
- src/main/java/org/springframework/samples/petclinic/web/ReclamacionValidator.java
- src/test/java/org/springframework/samples/petclinic/web/OfertaControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/ReclamacionControllerTests.java
Revisar ReclamacionControllerTests
> Corregidas algunas pruebas de OfertaController.

- src/main/java/org/springframework/samples/petclinic/model/Reclamacion.java
- src/main/java/org/springframework/samples/petclinic/web/ReclamacionController.java
- src/main/java/org/springframework/samples/petclinic/web/ReclamacionValidator.java
- src/main/resources/db/hsqldb/data.sql
- src/main/webapp/WEB-INF/jsp/reclamaciones/createOrUpdateReclamacionForm.jsp
- src/main/webapp/WEB-INF/jsp/reclamaciones/reclamacionesList.jsp
- src/test/java/org/springframework/samples/petclinic/service/ReclamacionServiceTests.java
- src/test/java/org/springframework/samples/petclinic/web/ReclamacionControllerTests.java
-De momento he comentado todo lo relacionado con la fecha de reclamación
y he añadido el atributo respuesta.
-He modificado los inserts de la BD.
-He añadido unos detalles al ReclamacionController.
-He modificado el ReclamacionValidator.
-He modificado las vistas asociadas a la reclamación.
> Cambiando Reclamación en general

- src/main/java/org/springframework/samples/petclinic/service/AdministradorService.java
- src/test/java/org/springframework/samples/petclinic/service/AdministradorServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/AdministradorServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/ClienteServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/ClienteServiceTestsSinMockito.java
Pruebas con Mockito (preguntar dudas)
> Mockitoo en Service

- src/main/java/org/springframework/samples/petclinic/web/AdministradorValidator.java
- src/main/java/org/springframework/samples/petclinic/web/CartaValidator.java
- src/main/java/org/springframework/samples/petclinic/web/ClienteValidator.java
- src/main/java/org/springframework/samples/petclinic/web/CocineroValidator.java
- src/main/java/org/springframework/samples/petclinic/web/CuentaValidator.java
- src/main/java/org/springframework/samples/petclinic/web/IngredienteValidator.java
- src/main/java/org/springframework/samples/petclinic/web/MesaValidator.java
- src/main/java/org/springframework/samples/petclinic/web/OfertaValidator.java
- src/main/java/org/springframework/samples/petclinic/web/OtrosValidator.java
- src/main/java/org/springframework/samples/petclinic/web/PizzaValidator.java
- src/main/java/org/springframework/samples/petclinic/web/ReservaValidator.java
> he arreglado validator ya que validaban cosas diferentes de las que

- src/test/java/org/springframework/samples/petclinic/service/OfertaServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/ReclamacionServiceTests.java
Aún no están todas las pruebas, faltan las de insert y delete pero no sé
muy bien cómo se hacen con Mockito.
> Avances en las pruebas de servicios de reclamación y oferta

- src/main/java/org/springframework/samples/petclinic/constant/ViewConstant.java
- src/main/java/org/springframework/samples/petclinic/web/PizzaController.java
- src/main/java/org/springframework/samples/petclinic/web/ReservaController.java
- src/test/java/org/springframework/samples/petclinic/web/PizzaControllerTests.java
El metodo get cliente activo da problemas para los tests
> PizzaControllerTests casi arreglados

- src/main/java/org/springframework/samples/petclinic/model/Reclamacion.java
- src/main/java/org/springframework/samples/petclinic/repository/ReclamacionRepository.java
- src/main/java/org/springframework/samples/petclinic/service/ReclamacionService.java
- src/main/java/org/springframework/samples/petclinic/web/OfertaController.java
- src/main/java/org/springframework/samples/petclinic/web/ReclamacionController.java
- src/main/webapp/WEB-INF/jsp/reclamaciones/reclamacionUser.jsp
- src/main/webapp/WEB-INF/jsp/welcome.jsp
- src/test/java/org/springframework/samples/petclinic/web/OfertaControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/ReclamacionControllerTests.java
Las pruebas del ReclamacionController no funcionan porque me da failed
to load Application Context y el problema está en el constructor de
reclamacion Controller
> Las pruebas de oferta ya funcionan.

- src/test/java/org/springframework/samples/petclinic/web/ReclamacionControllerTests.java
Aunque hay que seguir arreglando las pruebas
> Ya no da el error failed to load application context

- src/main/java/org/springframework/samples/petclinic/model/Reserva.java
- src/main/java/org/springframework/samples/petclinic/web/ClienteController.java
- src/main/java/org/springframework/samples/petclinic/web/OfertaController.java
- src/main/java/org/springframework/samples/petclinic/web/PizzaController.java
- src/main/java/org/springframework/samples/petclinic/web/ReclamacionController.java
- src/test/java/org/springframework/samples/petclinic/web/CartaControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/ClienteControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/CocineroControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/OfertaControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/PizzaControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/ReclamacionControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/RepartidorControllerTests.java
he estado arreglando y supervisando los tests de controladores. He hecho el test de clienteController y queda por arreglar reservaControllerTest que no funciona
> tests controladores

- src/main/java/org/springframework/samples/petclinic/web/AdministradorController.java
- src/main/java/org/springframework/samples/petclinic/web/AdministradorValidator.java
- src/main/java/org/springframework/samples/petclinic/web/CartaController.java
- src/main/webapp/WEB-INF/jsp/administradores/createOrUpdateAdministradorForm.jsp
- src/test/java/org/springframework/samples/petclinic/web/AdministradorControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/BebidaControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/CartaControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/MesaControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/OtrosControllerTests.java
arreglado pequeño error validador de administrador y sigo arreglando y depurando los tests de controlador
> tests y arreglo validador admin

- src/main/java/org/springframework/samples/petclinic/web/AdministradorController.java
- src/main/java/org/springframework/samples/petclinic/web/PedidoController.java
- src/main/webapp/WEB-INF/jsp/pedidos/pedidosList.jsp
En pedido no se veían los productos Otro, lo he areglado, procedo a hacer reglas de negocio o intentarlo.
> pequeño arreglo en carta y pedido

- src/main/webapp/WEB-INF/jsp/reservas/createOrUpdateReservaForm.jsp
- src/main/webapp/WEB-INF/tags/time.tag
> Reserva ya escoge el tiempo con un timepicker

- src/main/webapp/WEB-INF/jsp/cartas/createOrUpdateCartaForm.jsp
> datepicker carta

- src/main/resources/db/hsqldb/data.sql
- src/main/webapp/WEB-INF/jsp/pizzas/createOrUpdatePizzaForm.jsp
- src/main/webapp/WEB-INF/tags/checkbox.tag
- src/test/java/org/springframework/samples/petclinic/web/ReservaControllerTests.java
de un select. He añadido mas datos al sql de bebidas y otros
> Estoy intentando cambiar la lista de ingredientes a un checkbox en lugar

- src/main/java/org/springframework/samples/petclinic/repository/OfertaRepository.java
- src/main/java/org/springframework/samples/petclinic/service/OfertaService.java
- src/main/java/org/springframework/samples/petclinic/web/OfertaController.java
- src/main/webapp/WEB-INF/jsp/ofertas/createOrUpdateOfertaForm.jsp
volvemos a cambiar la decision de diseño
> Tocando oferta para unirla a producto,

- src/main/java/org/springframework/samples/petclinic/web/ReclamacionController.java
- src/main/java/org/springframework/samples/petclinic/web/ReservaController.java
- src/main/webapp/WEB-INF/jsp/mesas/mesasDisponibles.jsp
- src/main/webapp/WEB-INF/jsp/reclamaciones/confirmarReclamacion.jsp
- src/main/webapp/WEB-INF/jsp/reclamaciones/createOrUpdateReclamacionForm.jsp
- src/main/webapp/WEB-INF/jsp/reservas/reservasList.jsp
- src/test/java/org/springframework/samples/petclinic/web/ReclamacionControllerTests.java
He detectado un fallo en un jsp de reclamación que mañana corregiré y
haré más pruebas
> Reservas ya está terminado y pruebas de ReclamacionController funcionan

- src/main/java/org/springframework/samples/petclinic/model/Oferta.java
- src/main/java/org/springframework/samples/petclinic/model/Pizza.java
- src/main/java/org/springframework/samples/petclinic/model/Producto.java
- src/main/java/org/springframework/samples/petclinic/repository/OfertaRepository.java
- src/main/java/org/springframework/samples/petclinic/repository/PizzaRepository.java
- src/main/java/org/springframework/samples/petclinic/service/OfertaService.java
- src/main/java/org/springframework/samples/petclinic/web/OfertaController.java
- src/main/webapp/WEB-INF/jsp/AUXILIAR.jsp
- src/main/webapp/WEB-INF/jsp/cartas/cartasList.jsp
- src/main/webapp/WEB-INF/jsp/cartas/cartasListParaPedidos.jsp
- src/main/webapp/WEB-INF/jsp/cartas/verCarta.jsp
- src/main/webapp/WEB-INF/jsp/ofertas/createOrUpdateOfertaForm.jsp
- src/main/webapp/WEB-INF/jsp/pedidos/pedidoUser.jsp
- src/main/webapp/WEB-INF/jsp/pedidos/pedidosList.jsp
- src/main/webapp/WEB-INF/jsp/pedidos/resumenPedido.jsp
- src/main/webapp/WEB-INF/jsp/pedidos/verCartaParaPedido.jsp
> Oferta y Productos no se llevan bien, hay que arreglar el

- src/main/java/org/springframework/samples/petclinic/model/Oferta.java
- src/main/java/org/springframework/samples/petclinic/repository/OfertaRepository.java
- src/main/java/org/springframework/samples/petclinic/service/OfertaService.java
- src/main/java/org/springframework/samples/petclinic/web/CartaController.java
He hecho que cuando se borre un producto que se borre de su oferta y que 
se desactive la oferta. Además, he hecho que en la carta se muestren
solo las ofertas activadas.
> Carta y ofertas

- src/main/java/org/springframework/samples/petclinic/service/ClienteService.java
- src/main/java/org/springframework/samples/petclinic/service/CocineroService.java
- src/main/webapp/WEB-INF/jsp/clientes/clienteDetails.jsp
esto era debido a que se guardaba en la funcion antes el cocinero y el cliente que el user
> Cliente y cocinero no dejaban actualizar el nombre de usuario

- src/main/java/org/springframework/samples/petclinic/web/ClienteValidator.java
- src/main/java/org/springframework/samples/petclinic/web/CocineroValidator.java
- src/main/java/org/springframework/samples/petclinic/web/CuentaValidator.java
Los validadores admitian nombres y apellidos con numeros y fechas de
nacimiento superiores a la del dia actual
> Arreglar validadores cliente,cocinero y cuenta

- src/test/java/org/springframework/samples/petclinic/service/OfertaServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/OfertaServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/PedidoServiceTests.java
- src/test/java/org/springframework/samples/petclinic/service/PedidoServiceTestsSinMockito.java
Quizá habría que hacer algunas de casos negativos para PedidoService.
Las pruebas de OfertaService no están terminadas.
> Pruebas de PedidoService y OfertaService.

- src/main/java/org/springframework/samples/petclinic/web/AdministradorValidator.java
- src/main/java/org/springframework/samples/petclinic/web/CocineroValidator.java
- src/main/java/org/springframework/samples/petclinic/web/CuentaValidator.java
- src/main/java/org/springframework/samples/petclinic/web/RepartidorValidator.java
- src/main/webapp/WEB-INF/jsp/clientes/clientesList.jsp
- src/main/webapp/WEB-INF/jsp/exception.jsp
- src/main/webapp/WEB-INF/jsp/welcome.jsp
- src/main/webapp/WEB-INF/tags/menu.tag
- src/test/java/org/springframework/samples/petclinic/web/MesaControllerTests.java
arreglado validadores un poco y diseñando el menu de cuadros de la pagina principal
> varias cosas

- src/main/java/org/springframework/samples/petclinic/model/Bebida.java
- src/main/java/org/springframework/samples/petclinic/service/RepartidorService.java
- src/main/java/org/springframework/samples/petclinic/web/AdministradorValidator.java
- src/main/java/org/springframework/samples/petclinic/web/BebidaController.java
- src/main/java/org/springframework/samples/petclinic/web/CartaController.java
- src/main/java/org/springframework/samples/petclinic/web/CocineroValidator.java
- src/main/java/org/springframework/samples/petclinic/web/CuentaValidator.java
- src/main/java/org/springframework/samples/petclinic/web/RepartidorController.java
- src/main/java/org/springframework/samples/petclinic/web/RepartidorValidator.java
- src/main/resources/db/hsqldb/data.sql
- src/main/webapp/WEB-INF/jsp/bebidas/createOrUpdateBebidaForm.jsp
- src/main/webapp/WEB-INF/jsp/cartas/cartasList.jsp
- src/main/webapp/WEB-INF/jsp/clientes/clientesList.jsp
- src/main/webapp/WEB-INF/jsp/exception.jsp
- src/main/webapp/WEB-INF/jsp/pedidos/pedidoUser.jsp
- src/main/webapp/WEB-INF/jsp/pizzas/pizzasList.jsp
- src/main/webapp/WEB-INF/jsp/reservas/reservaUser.jsp
- src/main/webapp/WEB-INF/jsp/welcome.jsp
- src/main/webapp/WEB-INF/tags/menu.tag
- src/test/java/org/springframework/samples/petclinic/web/InformeControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/MesaControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/PedidoControllerTests.java
- src/test/java/org/springframework/samples/petclinic/web/RepartidorControllerTests.java
Reverts gii-is-DP1/dp1-2020-g2-09#476
> Revert "Raupargor2"

- src/main/java/org/springframework/samples/petclinic/repository/ReclamacionRepository.java
- src/main/java/org/springframework/samples/petclinic/service/ReclamacionService.java
- src/main/java/org/springframework/samples/petclinic/web/ReclamacionController.java
- src/test/java/org/springframework/samples/petclinic/service/ReclamacionServiceTests.java
En reclamaciones mostraba al usuario todas las reclamaciones, ahora solo ve sus reclamaciones.
> Arreglado reclamaciones

- src/main/resources/db/hsqldb/data.sql
> Subo la base de datos para que todos tengan un error resuelto y no haya

- src/main/java/org/springframework/samples/petclinic/model/Mesa.java
- src/main/java/org/springframework/samples/petclinic/web/MesaController.java
- src/test/java/org/springframework/samples/petclinic/service/AdministradorServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/BebidaServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/CartaServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/ClienteServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/CocineroServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/IngredienteServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/MesaServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/OfertaServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/OtrosServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/PedidoServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/PizzaServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/RepartidorServiceTestsSinMockito.java
- src/test/java/org/springframework/samples/petclinic/service/ReservaServiceTestsSinMockito.java
-Algún caso negativo de insert añadido.
-Quizá faltan casos negativos de update.
> Corrección en todas las pruebas de Servicios:
